include Makefile.kaldi
# Created by Hanna Kartynnik (hk3129).

BINFILES += append-xvectors fbank-to-mfcc

# Causes GNU Make warnings due to overridden targets. This is as intended.
include ../makefiles/default_rules.mk
